Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.

In [1]:
import numpy as np

In [18]:
list = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array( list )

array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Both have different data types list_ have list data type and array_list have array data type 

Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.

In [20]:
# Data type of elements in list 

for i in list:
    print( type( i ) )

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [22]:
for i in array_list:
    print( type( i ) )

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

In [24]:
array_list = np.array(object = list, dtype = int)

array_list

array([1, 2, 3, 4, 5])

In [26]:
for i in range( 5 ):
    print( "Data type of list: " , type( list[ i ] ) , "Data type of array_list items: " , type( array_list[ i ] ) )

Data type of list:  <class 'str'> Data type of array_list items:  <class 'numpy.int32'>
Data type of list:  <class 'str'> Data type of array_list items:  <class 'numpy.int32'>
Data type of list:  <class 'str'> Data type of array_list items:  <class 'numpy.int32'>
Data type of list:  <class 'str'> Data type of array_list items:  <class 'numpy.int32'>
Data type of list:  <class 'str'> Data type of array_list items:  <class 'numpy.int32'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [28]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

print( "Shape of matrix: " , num_array.shape , "Size of matrix: " , num_array.size )

Shape of matrix:  (2, 3) Size of matrix:  6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [32]:
# Creating an zeros matrix 

arr = np.zeros( ( 3 , 3 ) )

arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [35]:
# Identity matrix of size ( 5 , 5 )

arr = np.eye( 5 , 5 )

arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])